// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXe6rIKiu9Ab2t055LYXOJh-HUkfNnUM',
    appId: '1:990373375059:web:80a348b528c2e671aaeaa6',
    messagingSenderId: '990373375059',
    projectId: 'apprecycle-61c0a',
    authDomain: 'apprecycle-61c0a.firebaseapp.com',
    storageBucket: 'apprecycle-61c0a.firebasestorage.app',
    measurementId: 'G-59XMWZM0ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6l-P9CglgEluH7WMadwNyScAbAKj2NBg',
    appId: '1:990373375059:android:670ad7fa70df7817aaeaa6',
    messagingSenderId: '990373375059',
    projectId: 'apprecycle-61c0a',
    storageBucket: 'apprecycle-61c0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-1_AWJ8Wf0rIAvGt3-WbinwPGM_Yfvw',
    appId: '1:990373375059:ios:7962e4f66cc3b54eaaeaa6',
    messagingSenderId: '990373375059',
    projectId: 'apprecycle-61c0a',
    storageBucket: 'apprecycle-61c0a.firebasestorage.app',
    iosClientId: '990373375059-a6890frq2l12qj1vk3f2oj92p9mp8dhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.apprecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXe6rIKiu9Ab2t055LYXOJh-HUkfNnUM',
    appId: '1:990373375059:web:5f7d01edae33a0dcaaeaa6',
    messagingSenderId: '990373375059',
    projectId: 'apprecycle-61c0a',
    authDomain: 'apprecycle-61c0a.firebaseapp.com',
    storageBucket: 'apprecycle-61c0a.firebasestorage.app',
    measurementId: 'G-QH56ZS6QT1',
  );
}
